language: erlang
otp_release:
    - R15B02
    - R16

services:
    - riak
    - postgresql

notifications:
    irc:
        channels:
            - "irc.freenode.org#failfabric"   
    email: false

before_script:
    - psql -c 'CREATE DATABASE funtester_test;' -U postgres
    - psql -c 'CREATE DATABASE funtester_develop;' -U postgres

install: "make deps compile"
script: "make test-travis"

