language: erlang
otp_release:
    - R15B02
    - R14B04
services:
    - riak
notifications:
    irc:
        channels:
            - "irc.freenode.org#failfabric"   
    email: false
script: "make compile test"
